# Generated by Django 4.2.3 on 2023-08-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0002_customuser_sign"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="sign",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
